export const QUERY_KEY = {
  ME: 'ME',
  USER: 'USER',
  LOGIN: 'LOGIN/MUTATION',
  LOGOUT: 'LOGOUT/MUTATION',
  REGISTER: 'REGISTER/MUTATION',
  COURSE_DETAIL: 'COUSER_DETAIL',
  COURSE_NAVIGATE: 'COURSE_NAVIGATE',
  LESSON: 'LESSON',
  STATISTIC_COURSE: 'STATISTIC_COURSE',
};
