import './globals.css';
import type { Metadata } from 'next';
import ThemeRegistry from './ThemeRegistry';
import { Roboto } from 'next/font/google';
import CssBaseline from '@mui/material/CssBaseline';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['vietnamese'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <style>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </style>
      <body>
        <CssBaseline />
        <ThemeRegistry options={{ key: 'mui' }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
